# Generated by Django 6.0 on 2025-12-15 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCustomization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(default='Record Keeping Management System', max_length=200)),
                ('system_logo', models.TextField(blank=True, null=True)),
                ('login_background', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#4F46E5', max_length=20)),
                ('sidebar_gradient_start', models.CharField(default='#4F46E5', max_length=20)),
                ('sidebar_gradient_end', models.CharField(default='#7C3AED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_customization',
            },
        ),
        migrations.CreateModel(
            name='UserIdFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='TUPM', max_length=20)),
                ('admin_separator', models.CharField(default='_', max_length=5)),
                ('user_separator', models.CharField(default='-', max_length=5)),
                ('segment_count', models.IntegerField(default=2)),
                ('segment_lengths', models.JSONField(default=list)),
                ('custom_format', models.BooleanField(default=False)),
                ('custom_pattern_admin', models.CharField(default='TUPM_XX_XXXX', max_length=50)),
                ('custom_pattern_user', models.CharField(default='TUPM-XX-XXXX', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_id_format',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_position', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_info', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('resource', models.TextField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('ocr', 'OCR'), ('other', 'Other')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('ocr_content', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('file_data', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_field_values', models.JSONField(blank=True, default=dict)),
                ('personal_info', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectShare',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('full', 'Full Access')], default='view', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_given', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(related_name='shares_received', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_shares', to='records.document')),
            ],
            options={
                'db_table': 'direct_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow'), ('pink', 'Pink')], default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='records.folder'),
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Office', 'Office'), ('Department', 'Department'), ('College', 'College'), ('Division', 'Division'), ('Section', 'Section'), ('Unit', 'Unit'), ('Other', 'Other')], max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('head_position', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='records.organizationunit')),
            ],
            options={
                'db_table': 'organization_units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationShare',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('distribution_mode', models.CharField(choices=[('all-sub-units', 'All Sub-Units'), ('direct-children', 'Direct Children Only'), ('specific-units', 'Specific Units')], max_length=20)),
                ('selected_units', models.JSONField(blank=True, default=list, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_shares', to='records.document')),
                ('recipients', models.ManyToManyField(related_name='org_shares_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_shares_sent', to=settings.AUTH_USER_MODEL)),
                ('sent_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_from', to='records.organizationunit')),
            ],
            options={
                'db_table': 'organization_shares',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='records.organizationunit'),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('textarea', 'Long Text'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('show_in_documents', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_fields',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
