# Generated by Django 6.0.1 on 2026-02-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('resource', models.TextField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auth_api_au_timesta_b632f3_idx'), models.Index(fields=['user'], name='auth_api_au_user_e76334_idx'), models.Index(fields=['action'], name='auth_api_au_action_976b6f_idx'), models.Index(fields=['status'], name='auth_api_au_status_d8b667_idx')],
            },
        ),
    ]
