# Generated by Django 6.0.1 on 2026-02-02 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('ocr', 'OCR'), ('other', 'Other')], default='other', max_length=20)),
                ('folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file_data', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('ocr_content', models.TextField(blank=True, null=True)),
                ('personal_info', models.JSONField(blank=True, default=dict)),
                ('custom_field_values', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('shared_with', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='auth_api_do_created_2f2240_idx'), models.Index(fields=['created_by'], name='auth_api_do_created_3f421f_idx'), models.Index(fields=['is_deleted'], name='auth_api_do_is_dele_f8d6db_idx')],
            },
        ),
    ]
