# Generated by Django 6.0.1 on 2026-02-07 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_mode', models.CharField(choices=[('all-sub-units', 'All Sub-Units'), ('direct-children', 'Direct Children Only'), ('specific-units', 'Specific Units')], default='all-sub-units', max_length=30)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('selected_units', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_shares', to='auth_api.document')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_shares_sent', to=settings.AUTH_USER_MODEL)),
                ('sent_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_shares', to='auth_api.organizationunit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='auth_api_or_created_ab003e_idx'), models.Index(fields=['sent_by'], name='auth_api_or_sent_by_b8f2d8_idx')],
            },
        ),
    ]
