# Generated by Django 6.0.3 on 2026-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('passed_to_higher', 'Passed to Higher'), ('approved', 'Approved'), ('denied', 'Denied'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
