# Generated by Django 6.0.3 on 2026-03-29 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_desc', models.TextField(blank=True, null=True)),
                ('doc_path', models.CharField(max_length=500)),
                ('doc_uploaded', models.DateTimeField(auto_now_add=True)),
                ('user_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_timestamp', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('shared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_sent', to=settings.AUTH_USER_MODEL)),
                ('shared_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_shares',
            },
        ),
        migrations.CreateModel(
            name='OcrData',
            fields=[
                ('ocr_id', models.AutoField(primary_key=True, serialize=False)),
                ('ocr_extract', models.TextField()),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
            options={
                'db_table': 'ocr_data',
            },
        ),
    ]
