# Generated by Django 6.0.2 on 2026-04-07 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_alter_idformat_org'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('folder_color', models.CharField(default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.organization')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.folder')),
                ('user_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folders',
            },
        ),
        migrations.CreateModel(
            name='FolderShare',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.folder')),
                ('shared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_shares_sent', to=settings.AUTH_USER_MODEL)),
                ('shared_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folder_shares',
            },
        ),
    ]
