# Generated by Django 6.0.3 on 2026-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
