# Generated by Django 6.0.2 on 2026-04-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_doc_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_color',
        ),
    ]
