# Generated by Django 6.0.2 on 2026-04-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
