# Generated by Django 6.0.2 on 2026-04-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_category_desc_and_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('doc_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.category')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='documents.document')),
            ],
            options={
                'db_table': 'document_categories',
                'unique_together': {('doc', 'category')},
            },
        ),
    ]
