# Generated by Django 6.0.4 on 2026-04-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auto_category_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='detected_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
