# Generated by Django 6.0.2 on 2026-04-13 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0009_usercreationrequest_user_birthdate_and_more'),
        ('documents', '0010_add_share_msg_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owning_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to='authenticator.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='owning_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to='authenticator.organization'),
        ),
        migrations.AddField(
            model_name='foldershare',
            name='shared_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_shared_by', to='authenticator.organization'),
        ),
        migrations.AddField(
            model_name='foldershare',
            name='shared_with_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_shared_with', to='authenticator.organization'),
        ),
        migrations.RemoveField(
            model_name='foldershare',
            name='shared_by_user',
        ),
        migrations.RemoveField(
            model_name='foldershare',
            name='shared_to_user',
        ),
        migrations.AlterField(
            model_name='foldershare',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_shares', to='documents.folder'),
        ),
        migrations.AlterUniqueTogether(
            name='foldershare',
            unique_together={('folder', 'shared_with_org')},
        ),
    ]
