# Generated by Django 6.0.2 on 2026-04-13 18:06

from django.db import migrations


def forwards(apps, schema_editor):
    Folder = apps.get_model('documents', 'Folder')
    Document = apps.get_model('documents', 'Document')
    FolderShare = apps.get_model('documents', 'FolderShare')

    # Backfill folder ownership and creator trace.
    for folder in Folder.objects.select_related('org', 'user_index').all():
        updates = []
        if folder.owning_org_id is None:
            if folder.org_id is not None:
                folder.owning_org_id = folder.org_id
                updates.append('owning_org')
            elif folder.user_index_id is not None and getattr(folder.user_index, 'org_id', None) is not None:
                folder.owning_org_id = folder.user_index.org_id
                updates.append('owning_org')

        if folder.created_by_user_id is None and folder.user_index_id is not None:
            folder.created_by_user_id = folder.user_index_id
            updates.append('created_by_user')

        if updates:
            folder.save(update_fields=updates)

    # Backfill document ownership and uploader trace.
    for doc in Document.objects.select_related('folder', 'folder__owning_org', 'folder__org', 'user_index').all():
        updates = []
        if doc.owning_org_id is None:
            if doc.folder_id is not None and getattr(doc.folder, 'owning_org_id', None) is not None:
                doc.owning_org_id = doc.folder.owning_org_id
                updates.append('owning_org')
            elif doc.folder_id is not None and getattr(doc.folder, 'org_id', None) is not None:
                doc.owning_org_id = doc.folder.org_id
                updates.append('owning_org')
            elif doc.user_index_id is not None and getattr(doc.user_index, 'org_id', None) is not None:
                doc.owning_org_id = doc.user_index.org_id
                updates.append('owning_org')

        if doc.uploaded_by_user_id is None and doc.user_index_id is not None:
            doc.uploaded_by_user_id = doc.user_index_id
            updates.append('uploaded_by_user')

        if updates:
            doc.save(update_fields=updates)

    # Folder shares no longer store user sender/receiver.
    # Backfill the sender org from folder ownership when missing.
    for share in FolderShare.objects.select_related('folder', 'folder__owning_org').all():
        if share.shared_by_org_id is None and share.folder_id is not None and getattr(share.folder, 'owning_org_id', None) is not None:
            share.shared_by_org_id = share.folder.owning_org_id
            share.save(update_fields=['shared_by_org'])


def backwards(apps, schema_editor):
    # Intentionally no-op: this migration enriches data for new ownership model.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_foldershare_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
