# Generated by Django 6.0.2 on 2026-04-13 18:27

import django.db.models.deletion
from django.db import migrations, models


def validate_no_null_ownership(apps, schema_editor):
    Folder = apps.get_model('documents', 'Folder')
    Document = apps.get_model('documents', 'Document')

    folder_nulls = Folder.objects.filter(owning_org__isnull=True).count()
    document_nulls = Document.objects.filter(owning_org__isnull=True).count()

    if folder_nulls or document_nulls:
        raise RuntimeError(
            f'Cannot enforce non-null ownership yet: folder_nulls={folder_nulls}, document_nulls={document_nulls}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_backfill_org_ownership'),
    ]

    operations = [
        migrations.RunPython(validate_no_null_ownership, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='document',
            name='owning_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to='authenticator.organization'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owning_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to='authenticator.organization'),
        ),
    ]
