# Generated by Django 6.0.3 on 2026-04-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_archive_batch_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='documents.category'),
        ),
    ]
