# Generated by Django 6.0.3 on 2026-04-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_folder_folder_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentarchive',
            new_name='document_ar_source__47e18a_idx',
            old_name='document_arc_source__e58d7e_idx',
        ),
        migrations.RenameIndex(
            model_name='folderarchive',
            new_name='folder_arch_source__26efc0_idx',
            old_name='folder_archi_source__74cb0c_idx',
        ),
    ]
