# Generated by Django 6.0.4 on 2026-04-28 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0010_alter_idformat_prefix_nullable'),
        ('documents', '0019_rename_document_arc_source__e58d7e_idx_document_ar_source__47e18a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApprovalRequest',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('passed_to_higher', 'Passed to Higher')], default='pending', max_length=20)),
                ('review_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='documents.document')),
                ('passed_to_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_received_higher', to='authenticator.organization')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('requested_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_received', to='authenticator.organization')),
                ('requesting_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to='authenticator.organization')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_approval_requests',
            },
        ),
    ]
