# Generated by Django 6.0.3 on 2026-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTheme',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_name', models.CharField(max_length=255)),
                ('sys_abbr', models.CharField(max_length=50)),
                ('sys_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('sys_backg', models.CharField(blank=True, max_length=500, null=True)),
                ('is_theme_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'system_themes',
            },
        ),
    ]
