# Generated by Django 6.0.2 on 2026-03-29 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtheme',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='systemtheme',
            name='primary_color',
            field=models.CharField(default='#4F46E5', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='systemtheme',
            name='sidebar_gradient_end',
            field=models.CharField(default='#7C3AED', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='systemtheme',
            name='sidebar_gradient_start',
            field=models.CharField(default='#4F46E5', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='systemtheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemtheme',
            name='sys_backg',
            field=models.ImageField(blank=True, null=True, upload_to='system_assets/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='systemtheme',
            name='sys_logo',
            field=models.ImageField(blank=True, null=True, upload_to='system_assets/logos/'),
        ),
    ]
