# Generated by Django 6.0.3 on 2026-03-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_systemtheme_created_at_systemtheme_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemtheme',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='systemtheme',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='systemtheme',
            name='sidebar_gradient_end',
        ),
        migrations.RemoveField(
            model_name='systemtheme',
            name='sidebar_gradient_start',
        ),
        migrations.RemoveField(
            model_name='systemtheme',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='systemtheme',
            name='sys_backg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='systemtheme',
            name='sys_logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
