# Generated by Django 6.0.2 on 2026-04-10 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_remove_systemtheme_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemtheme',
            name='sidebar_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('teal', 'Teal'), ('cyan', 'Cyan')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='systemtheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
