# Generated by Django 6.0.2 on 2026-04-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0004_add_sidebar_color_and_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtheme',
            name='sys_backg',
            field=models.ImageField(blank=True, null=True, upload_to='system/'),
        ),
        migrations.AlterField(
            model_name='systemtheme',
            name='sys_logo',
            field=models.ImageField(blank=True, null=True, upload_to='system/'),
        ),
    ]
