# Generated by Django 6.0.2 on 2026-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0005_alter_systemtheme_sys_backg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtheme',
            name='sidebar_color',
            field=models.CharField(default='#4F46E5', help_text='Color name (blue, indigo, etc) or hex code (#RRGGBB)', max_length=7),
        ),
    ]
