# Generated by Django 5.2.8 on 2025-12-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
