# Generated by Django 6.0.3 on 2026-04-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_customuser_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idformat',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.organization'),
        ),
    ]
