# Generated by Django 6.0.2 on 2026-04-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_alter_idformat_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_pos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
