# Generated by Django 5.2.8 on 2025-12-16 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create Document'), ('view', 'View Document'), ('edit', 'Edit Document'), ('delete', 'Delete Document'), ('download', 'Download Document'), ('share', 'Share Document'), ('upload', 'Upload Document')], max_length=20)),
                ('target_doc', models.CharField(blank=True, help_text='Document name or ID that was acted upon', max_length=255, null=True)),
                ('log_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_timestamp'],
                'indexes': [models.Index(fields=['-log_timestamp'], name='authenticat_log_tim_69ffe9_idx'), models.Index(fields=['user', '-log_timestamp'], name='authenticat_user_id_7865e4_idx')],
            },
        ),
    ]
