# Generated by Django 6.0.2 on 2026-04-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_customuser_user_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreationRequest',
            fields=[
                ('request_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('email_add', models.EmailField(max_length=254, unique=True)),
                ('user_pos', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authenticator.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_creation_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
