# Generated by Django 6.0.3 on 2026-04-11 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_usercreationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreationrequest',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercreationrequest',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
