# Generated by Django 6.0.3 on 2026-04-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0006_usercreationrequest_claimed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idformat',
            name='org',
        ),
    ]
