# Generated by Django 6.0.3 on 2026-04-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_remove_idformat_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
