# Generated by Django 6.0.3 on 2026-04-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0012_customuser_must_change_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='must_change_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_changed_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
