# Generated by Django 6.0.4 on 2026-04-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0014_remembereddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remembereddevice',
            name='device_fingerprint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='remembereddevice',
            name='device_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='remembereddevice',
            unique_together={('user', 'device_token', 'device_fingerprint')},
        ),
    ]
